site_name: Aether Help
pages:
- Home: index.md
- Getting Started:
  - Installing Aether: installing.md
  - Getting Started: gettingstarted.md
- Guides:
  - Callbook Lookup: callbooklookup.md

theme: amelia
