site_name: Aether Help
pages:
- Home: index.md
- Getting Started:
  - Installing Aether: installing.md
  - Getting Started: gettingstarted.md
  - Callbook Lookup: callbooklookup.md
- Guides:
  - Callbook Lookup: callbooklookup.md
  - Logbook of the World:
    - Overview: lotw/lotwsetup.md
    - Certificates:
      - Requesting a Certificate: lotw/requestcertificate.md
      - Installing a Certificate: lotw/installcertificate.md
      - Troubleshooting Certificates: lotw/certificatetroubleshooting.md
    - LoTW Settings: lotw/lotwsettings.md
    - Syncing with LoTW: lotw/syncinglotw.md
    - Troubleshooting LoTW: lotw/lotwtroubleshooting.md
- FAQ:
  - TX/RX Exch.: faq/txrxexch.md

theme: amelia
