site_name: Aether Help
pages:
- Home: index.md
- Getting Started:
  - Installing Aether: installing.md
  - Getting Started: gettingstarted.md
  - Callbook Lookup: callbooklookup.md
- Guides:
  - Callbook Lookup: callbooklookup.md
  - Logbook of the World:
    - Setup: lotw/lotwsetup.md
    - Certificates:
      - Requesting a Certificate: lotw/requestcertificate.md
      - Installing a Certificate: lotw/installcertificate.md
      - Exporting a p12 from TQSL: lotw/exportp12fromtqsl.md
      - Troubleshooting Certificates: lotw/certificatetroubleshooting.md
    - LoTW Settings: lotw/lotwsettings.md
    - Syncing with LoTW: lotw/syncinglotw.md
    - Troubleshooting:
      - Overview: lotw/lotwtroubleshootingoverview.md
      - Certificates: lotw/certificatetroubleshooting.md
      - Uploads to LoTW: lotw/lotwuploadtroubleshooting.md
- FAQ:
  - TX/RX Exch.: faq/txrxexch.md
  - Lost Logbook: faq/lostlog.md
  - Aether Betas: faq/beta.md

theme: amelia
