site_name: Aether Help
pages:
- Home: index.md
- Getting Started:
  - Installing Aether: installing.md
  - Getting Started: gettingstarted.md
  - Callbook Lookup: callbooklookup.md
- Guides:
  - Callbook Lookup: callbooklookup.md
- FAQ:
  - TX/RX Exch.: txrxexch.md

theme: amelia
